# Change these first
owner: slovak-egov # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Web MIRRI SR
    url: https://www.mirri.gov.sk
  - name: Web MV SR
    url: https://www.minv.sk
  - name: Web MZ SR
    url: https://health.gov.sk
  - name: Web MD SR
    url: https://www.mindop.sk
  - name: Web MF SR
    url: https://www.mfsr.sk/sk
  - name: Web MH SR
    url: https://www.mhsr.sk
  - name: Web MK SR
    url: https://www.culture.gov.sk
  - name: Web MO SR
    url: https://www.mosr.sk
  - name: Web MP SR
    url: https://www.mpsr.sk
  - name: Web MPSVaR SR
    url: https://www.employment.gov.sk/sk
  - name: Web MŠVVaM SR
    url: https://www.minedu.sk
  - name: Web MZV SR
    url: https://www.mzv.sk
  - name: Web MŽP SR
    url: https://www.minzp.sk
  - name: Web MCRS SR
    url: https://mincrs.sk
  - name: Web MS SR
    url: https://www.justice.gov.sk
  - name: Web Slovensko.sk (ÚPVS)
    url: https://www.slovensko.sk
  - name: Web NASES
    url: https://nases.gov.sk
  - name: Web Sociálna poisťovňa
    url: https://www.socpoist.sk
  - name: Slov Lex
    url: https://www.slov-lex.sk
  - name: Centrálny register zmluv SR
    url: https://crz.gov.sk
  - name: MetaIS
    url: https://metais.slovensko.sk
  - name: Web Centrálna Integračná Platforma
    url: https://cip.gov.sk/portal
  - name: Web data.gov.sk
    url: https://data.gov.sk
  - name: Národný katalóg otvorených dát
    url: https://data.slovensko.sk
  - name: Web Dátová interoperabilita
    url: https://znalosti.gov.sk
  - name: Portál ID-SK
    url: https://idsk.gov.sk
  - name: SVM Enrollment Portál
    url: https://ep.slovensko.sk/titulna-stranka
  - name: Repo eID MV SR
    url: https://eidas.minv.sk/download
  - name: Katastrálna mapa
    url: https://kataster.skgeodesy.sk/GisPortal
  - name: Web SNCA
    url: https://snca.gov.sk
  - name: GovNet Mail GW
    url: mail.gov.sk
    port: 25
    check: "tcp-ping"
#  - name: SVM API endpoint
#    url: https://api.slovensko.sk
#    method: GET
#    headers:
#      - "Content-Type: application/json"
#      - 'Accept: application/json'
#  - name: ITMS 1
#    url: https://www.itms.sk
#  - name: ITMS2014+
#    url: https://www.itms2014.sk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://mirri.gov.sk/wp-content/uploads/2020/06/logo-miiri-farebne-sk-01-2.svg
  name: Uptime Slovak eGov public endpoints
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
